#!/usr/bin/bash

yarn docs

DIFF_SIZE=$(git diff docs/API.md | wc -l)

if [[ ! $DIFF_SIZE -eq 0 ]]; then
    echo "Regenerate documentation using yarn docs and commit the changes."
    echo $(git diff)
    exit 0
fi
