#!/usr/bin/bash

#
# Tests are executed using a built version of the runner.
#
# This will first build the package, install it in a temporary
# environment and run the test suite with it.
#


rm -rf integration-build.tgz dist
yarn pack --out integration-build.tgz

mkdir .tests

echo "{}" > .tests/package.json
touch .tests/yarn.lock

(
    cd .tests
    yarn cache clean
    yarn add ../integration-build.tgz ts-node
    yarn womm ../tests --ts --workers=2
)

rm -rf .tests
